# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4
  
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 1m
  
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1
  
  # include test files or not, default is true
  tests: true
  
  
# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number
  
  # print lines of code with issue, default is true
  print-issued-lines: true
  
  # print linter name in the end of issue text, default is true
  print-linter-name: true
  
  
# all available settings of specific linters
linters-settings:
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 100
    # tab width in spaces. Default to 1.
    tab-width: 4
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 150
  
  
linters:
  enable-all: true
  disable:
    # disable typecheck because of an error unexpected:
    #   "C source files not allowed when not using cgo or SWIG: test_syscalls.c"
    - typecheck
    - gochecknoglobals
  
  
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - linters:
        - gosec
      text: "weak cryptographic primitive"
  
    - path: _test\.go
      linters:
        - scopelint
      text: "Using the variable on range scope .* in function literal"
  